/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BookTic;

import java.awt.print.PrinterException;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ngenii
 */
public class Receipt extends javax.swing.JFrame {
    String type="";
    String luggage="no";
    String ticketo="";
    String FullName="";
    int idno=0;
    String DateOfDeparture;
    String mu ="yyyy-MM-dd";

    /**
     * Creates new form Receipt
     */
    public Receipt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        cbfrom = new javax.swing.JComboBox<>();
        cbto = new javax.swing.JComboBox<>();
        chluggage = new javax.swing.JCheckBox();
        rbstandard = new javax.swing.JRadioButton();
        rbfc = new javax.swing.JRadioButton();
        jdate = new com.toedter.calendar.JDateChooser();
        jSeparator1 = new javax.swing.JSeparator();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sylfaen", 2, 14)); // NOI18N
        jLabel1.setText("TICKET");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 0, 100, 34));

        jLabel2.setText("From");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 81, 103, 25));

        jLabel3.setText("To");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 131, 103, 22));

        jLabel4.setText(" Luggage");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 113, 24));

        jLabel5.setText("Type");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 103, 26));

        jLabel6.setText("Departure date");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 265, 113, 22));

        jButton1.setText("RESET");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 328, -1, -1));

        jButton2.setText("CHECK RECEIPT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 328, 124, -1));

        jButton3.setText("PRINT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 328, -1, -1));

        cbfrom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select origin", "Nairobi", "Voi", "Mombasa" }));
        jPanel1.add(cbfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 83, 145, -1));

        cbto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select origin", "Nairobi", "Voi", "Mombasa" }));
        cbto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtoActionPerformed(evt);
            }
        });
        jPanel1.add(cbto, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 132, 145, -1));

        chluggage.setText("YES");
        chluggage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chluggageActionPerformed(evt);
            }
        });
        jPanel1.add(chluggage, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 120, -1));

        rbstandard.setText("Standard");
        rbstandard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rbstandardMouseEntered(evt);
            }
        });
        rbstandard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbstandardActionPerformed(evt);
            }
        });
        jPanel1.add(rbstandard, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 223, -1, -1));

        rbfc.setText("First Class");
        rbfc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rbfcMouseEntered(evt);
            }
        });
        rbfc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbfcActionPerformed(evt);
            }
        });
        jPanel1.add(rbfc, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 223, 100, -1));
        jPanel1.add(jdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 267, 152, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 255, 204));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 40, 243, 10));

        jButton4.setText("BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 440));

        area.setColumns(20);
        area.setFont(new java.awt.Font("Sylfaen", 2, 18)); // NOI18N
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 330, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       int k;
       String sl="";
       k=1325 + (int) (Math.random()*4238);
       sl+=k+1325;
       ticketo=sl;
       
       FullName=JOptionPane.showInputDialog("Enter Full Names");
       String IdNo=JOptionPane.showInputDialog("Enter id number");
       idno = Integer.parseInt(IdNo);
       
       
       SimpleDateFormat b=new SimpleDateFormat(mu);
           Date DateOfDepartur=jdate.getDate();
           String DateOfDeparture=b.format(DateOfDepartur);
        
        
        area.setText("********************************************\n");
        area.setText(area.getText() +"*******  TICKET RECEIPT  *********\n");
        area.setText(area.getText() +"********************************************\n");
        area.setText(area.getText() + "Ticket number      :    " + ticketo+"\n");
        area.setText(area.getText() + "Name      :    " + FullName+"\n");
        area.setText(area.getText() + "ID Number      :    " + idno+"\n");
        Date obj =new Date();
        String date=obj.toString();
        area.setText(area.getText() + date +"\n");
        area.setText(area.getText() +"********************************************\n");
        area.setText(area.getText() + "Destination        :    " +cbfrom.getSelectedItem()+"\n");
        area.setText(area.getText() + "To                 :    " +cbto.getSelectedItem()+"\n");
        area.setText(area.getText() + "Luggage            :    " +luggage +"\n");
        
        area.setText(area.getText() + "Type:              :    " +type +"\n");
        area.setText(area.getText() + "Departure date     : " +DateOfDeparture+"\n");
        area.setText(area.getText() +"********************************************\n");
        float total = 0;
        String fare = "0";
        if(!chluggage.isSelected()){
            if((cbfrom.getSelectedItem().equals("Nairobi")&&cbto.getSelectedItem().equals("Voi")||cbfrom.getSelectedItem().equals("Voi")&&cbto.getSelectedItem().equals("Nairobi"))&&type=="Standard"){
                total= 600;
            }else{
                total=800;
            }
            if((cbfrom.getSelectedItem().equals("Nairobi")&&cbto.getSelectedItem().equals("Mombasa")||cbfrom.getSelectedItem().equals("Mombasa")&&cbto.getSelectedItem().equals("Nairobi"))&&type=="Standard"){
                total= 800;
            }else{
                total=1000;
            }
            if((cbfrom.getSelectedItem().equals("Voi")&&cbto.getSelectedItem().equals("Mombasa")||cbfrom.getSelectedItem().equals("Mombasa")&&cbto.getSelectedItem().equals("Voi"))&&type=="Standard"){
                total= 400;
            }else{
                total=600;
            }
        }else{
            if((cbfrom.getSelectedItem().equals("Nairobi")&&cbto.getSelectedItem().equals("Voi")||cbfrom.getSelectedItem().equals("Voi")&&cbto.getSelectedItem().equals("Nairobi"))&&type=="Standard"){
                total=650 ;
            }else{
                total=850;
            }
            if((cbfrom.getSelectedItem().equals("Nairobi")&&cbto.getSelectedItem().equals("Mombasa")||cbfrom.getSelectedItem().equals("Mombasa")&&cbto.getSelectedItem().equals("Nairobi"))&&type=="Standard"){
                total= 855;
            }else{
                total=1055;
            }
            if((cbfrom.getSelectedItem().equals("Voi")&&cbto.getSelectedItem().equals("Mombasa")||cbfrom.getSelectedItem().equals("Mombasa")&&cbto.getSelectedItem().equals("Voi"))&&type=="Standard"){
                total= 450;
            }else{
                total=656;
            }
        }
       // fare=String.valueOf(total);
        fare =String.format("%.2f",total);
        area.setText(area.getText() +"********************************************\n");
        area.setText(area.getText() +"Total :   "+"KSH  " + fare +"\n");
        area.setText(area.getText() +"********************************************\n");
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        area.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            // TODO add your handling code here:
            area.print();
        } catch (PrinterException ex) {
            Logger.getLogger(Receipt.class.getName()).log(Level.SEVERE, null, ex);
        }
        String uname="root";
        String pass="kipngeno33";
        String conn_string="jdbc:mysql://localhost:3306/TrainTickets";
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            java.sql.Connection conn = DriverManager.getConnection(conn_string,uname,pass);
            Statement stmt =(Statement) conn.createStatement();
            //String sql = "select TicketNo from tickets ";
            
 
            String From=(String) cbfrom.getSelectedItem();
            String To=(String) cbto.getSelectedItem();
            //boolean Luggagge=chluggage.isSelected();
            String Luggage=luggage;
            String Type=type;
            SimpleDateFormat b=new SimpleDateFormat("MM-dd-yyyy");
           // Date DateOfDeparture=jdate.getDate();
           String DateOfDeparture=b.format(jdate.getDate());
            //String ttt=String.valueOf(DateOfDeparture);
            Date obj =new Date();
            String DateOfPurchase=obj.toString();
            String insert = "INSERT INTO tickets VALUES('"+From+"','"+To+"','"+Luggage+"','"+Type+"','"+DateOfDeparture+"','"+ticketo+"','"+idno+"','"+DateOfPurchase+"');";
            stmt.executeUpdate(insert);
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null,"Thank you for buying ticket");
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cbtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbtoActionPerformed

    private void rbstandardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbstandardMouseEntered
        // TODO add your handling code here:
       
    }//GEN-LAST:event_rbstandardMouseEntered

    private void rbfcMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbfcMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_rbfcMouseEntered

    private void rbstandardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbstandardActionPerformed
        // TODO add your handling code here:
        if(rbstandard.isSelected()){
            rbfc.setSelected(false);
            type="standard";
        }
    }//GEN-LAST:event_rbstandardActionPerformed

    private void rbfcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbfcActionPerformed
        // TODO add your handling code here:
        if(rbfc.isSelected()){
            rbstandard.setSelected(false);
            type="first class";
        }
    }//GEN-LAST:event_rbfcActionPerformed

    private void chluggageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chluggageActionPerformed
        // TODO add your handling code here:
        if(chluggage.isSelected()){
            luggage = "Yes";
        }else{
            luggage = "No";
        }
    }//GEN-LAST:event_chluggageActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Homepage hom= new Homepage();
        hom.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Receipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JComboBox<String> cbfrom;
    private javax.swing.JComboBox<String> cbto;
    private javax.swing.JCheckBox chluggage;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private com.toedter.calendar.JDateChooser jdate;
    private javax.swing.JRadioButton rbfc;
    private javax.swing.JRadioButton rbstandard;
    // End of variables declaration//GEN-END:variables
}
